# This is a configuration file for automated testing. You must edit the host ip
# address and follow any additional steps in the demo-server/README.md
---
application_name: AuTHRity_OPC_UA_Server
application_uri: authrity:opcua-server
product_uri: authrity:opcua-server
create_sample_keypair: true
# Cert must be correct for hostname
certificate_path: own/cert.der
private_key_path: private/private.pem
certificate_validation:
  trust_client_certs: true
  check_time: false
pki_dir: "./pki"
#discovery_server_url: ""
tcp_config:
  hello_timeout: 5
  # Host must be the computer name and must match settings in test app
  host: localhost
  port: 4855
limits:
  clients_can_modify_address_space: false
  max_subscriptions: 100
  max_monitored_items_per_sub: 1000
  max_monitored_item_queue_size: 10
  max_array_length: 1000
  max_string_length: 65535
  max_byte_string_length: 65535
  min_sampling_interval: 0.1
  min_publishing_interval: 0.1
locale_ids:
  - en
user_tokens:
  my_admin:
    user: admin
    pass: password
  hmi:
    user: hmi
    pass: password
  apc_engine:
    user: apc_engine
    pass: password
  virtual_plant:
    user: virtual_plant
    pass: password
  sample_x509_user:
    user: sample_x509
    x509: "./users/sample_x509.der"
  virtual_plant_x509:
    user: virtual_plant
    x509: "./users/virtual_plant.der"
  hmi_x509:
    user: HMI
    x509: "./users/HMI.der"
discovery_urls:
  - opc.tcp://localhost:4855/
default_endpoint: basic256sha256_sign_encrypt
endpoints:
  basic256sha256_sign_encrypt:
    path: /
    security_policy: Basic256Sha256
    security_mode: SignAndEncrypt
    security_level: 14
    password_security_policy: ~
    user_token_ids:
      - my_admin
      - hmi
      - virtual_plant
      - apc_engine
      - hmi_x509
      - sample_x509_user