[package]
name = "authrity-hmi"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
# 1. Async Runtime
tokio = { version = "1", features = ["full"] }

# 2. Web Server & HTTPS
axum = { version = "0.7", features = ["ws", "macros", "multipart"] }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["fs", "trace", "cors"] }

# 3. Authentication (Login Session)
tower-sessions = "0.12" 
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
argon2 = "0.5"
time = "0.3"

# 4. Data Handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }

# 5. OPC UA 
async-opcua = { version = "0.17", features = ["client"] }

# 6. Time-Series Database
questdb-rs = "6.1"
reqwest = { version = "0.12", features = ["json", "multipart"] }
urlencoding = "2.1"

# 7. Error Handling & Logging
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# 7. Embedding Frontend (Single Executable)
rust-embed = "8.0"
toml = "0.9.10"

futures = "0.3"
