[graph]
all-features = true

[licenses]
confidence-threshold = 0.93
unused-allowed-license = "allow"

allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "MPL-2.0",
  "Zlib",
  "Unicode-3.0",
]

[licenses.private]
ignore = true
